-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Jun 21, 2024 at 12:34 PM
-- Server version: 10.11.7-MariaDB-cll-lve
-- PHP Version: 7.2.34

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `u496524825_shreeji_blog`
--

-- --------------------------------------------------------

--
-- Table structure for table `blog`
--

CREATE TABLE `blog` (
  `id` int(100) NOT NULL,
  `keyword` varchar(256) NOT NULL,
  `title` varchar(256) NOT NULL,
  `message` text NOT NULL,
  `metadata` text NOT NULL,
  `image` varchar(256) NOT NULL,
  `slug` varchar(256) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `blog`
--

INSERT INTO `blog` (`id`, `keyword`, `title`, `message`, `metadata`, `image`, `slug`) VALUES
(47, 'OrganicLiquid fertilizer supplier in  russia', 'Best OrganicLiquid fertilizer supplier in  russia', '<p>Liquid fertilizer, also known as liquid plant food or liquid nutrient solution, is a concentrated form of fertilizer that is dissolved in water for application to plants. It provides essential nutrients to plants in a readily available form, promoting growth, flowering, and overall health. Here\'s an overview of liquid fertilizer:</p>', 'At Shreeji Agro & Fertilizers, we\'re committed to transforming agriculture through innovation and sustainability. Our mission is to provide farmers with cutting-edge solutions and high-quality fertilizers that optimize crop yields and promote environmental stewardship.', '', 'OrganicLiquid-fertilizer-supplier-in-russia'),
(48, 'Liquid fertilizer supplier in canada', 'Best Liquid fertilizer supplier in canada', '<p>Organic Liquid Fertilizers: Made from natural sources such as compost, seaweed extracts, fish emulsion, or animal manure. They provide nutrients and also improve soil structure and microbial activity.</p>', 'With a focus on research and development, we offer a diverse range of products tailored to meet the unique needs of every farmer. From traditional fertilizers to advanced bio-fertilizers and specialty nutrients, we have everything you need to nurture your crops and maximize profitability.', '', 'Liquid-fertilizer-supplier-in-canada'),
(49, 'Liquid fertilizer exporter in canada', 'Best Liquid fertilizer exporter in canada', '<p>Specialty Liquid Fertilizers: Designed for specific purposes, such as promoting flowering (high phosphorus), greening (high nitrogen), or correcting nutrient deficiencies (e.g., iron for chlorosis).\r\n</p>', 'Choose Shreeji Agro & Fertilizers for unparalleled quality, innovation, and sustainability in agriculture. With our commitment to excellence, expert guidance, and customized solutions, we empower farmers to achieve their goals while preserving the environment. Trust in our expertise, dedication to customer satisfaction, and transparent practices to drive success on your farm.', '', 'Liquid-fertilizer-exporter-in-canada'),
(50, 'Liquid fertilizer exporter in china', 'Best Liquid fertilizer exporter in china', '<p>Quick Absorption: Nutrients are readily available to plants, allowing for rapid uptake through leaves and roots.\r\nConvenience: Easy to apply via foliar spraying or direct soil drenching, suitable for both indoor and outdoor plants.\r\nCustomizable: Can be tailored to specific plant needs or growth stages by adjusting nutrient ratios or adding supplements like growth enhancers or biostimulants.\r\nImmediate Impact: Provides an immediate boost to plants showing signs of nutrient deficiency or stress.</p>', 'At Shreeji Agro & Fertilizers, quality service is our hallmark. We are committed to delivering excellence in every aspect of our operations, from product development to customer support.', '', 'Liquid-fertilizer-exporter-in-china'),
(51, 'Organic Liquid fertilizer supplier in usa', 'Best Organic Liquid fertilizer supplier in usa', '<p>Spraying liquid fertilizer directly onto leaves allows for quick absorption of nutrients. Ideal for correcting deficiencies or promoting growth during periods of rapid growth.\r\nSoil Drenching: Pouring liquid fertilizer directly onto the soil around plants ensures nutrients reach the root zone. Effective for ongoing nutrient maintenance and root development.</p>', ' Our mission is to provide farmers with cutting-edge solutions and high-quality fertilizers that optimize crop yields and promote environmental stewardship.', '', 'Organic-Liquid-fertilizer-supplier-in-usa'),
(52, 'Liquid fertilizer supplier in morocco', 'Best Liquid fertilizer supplier in morocco', '<p>Considerations for Use\r\nDilution: Always follow manufacturer\'s instructions for diluting liquid fertilizers to prevent over-fertilization, which can harm plants.\r\nFrequency: Apply liquid fertilizers according to plant needs and growth stages. Too frequent application can lead to nutrient imbalances or salt buildup in the soil.\r\nStorage: Store liquid fertilizers in a cool, dry place away from direct sunlight to maintain their efficacy and prevent degradation.</p>', 'At Shreeji Agro & Fertilizers, we pride ourselves on providing quick and responsive support to our valued customers. Whether you have questions about our products, need technical assistance, or require help with an order, our dedicated customer support team is here to assist you promptly. ', '', 'Liquid-fertilizer-supplier-in-morocco'),
(55, 'Liquid fertilizer supplier in saudi arabia', 'Best Liquid fertilizer supplier in saudi arabia', '<p>Nutrient Runoff: Proper application and dosage help minimize nutrient runoff into waterways, which can contribute to algae blooms and water pollution.\r\nSustainable Practices: Consider using organic or slow-release liquid fertilizers and implementing integrated nutrient management practices to reduce environmental impact.\r\nConclusion\r\nLiquid fertilizers are a valuable tool for gardeners and farmers to enhance plant nutrition and promote healthy growth. By understanding their types, benefits, application methods, and environmental considerations, you can effectively integrate liquid fertilizers into your gardening or agricultural practices to achieve optimal plant health and productivity.</p>', 'Shreeji Agro & Fertilizers embraces modern technology to revolutionize agriculture and empower farmers. Through cutting-edge innovations in fertilizer formulation, precision farming techniques, and data-driven insights, we help farmers optimize resource use, maximize yields, and enhance sustainability.', '', 'Liquid-fertilizer-supplier-in-saudi-arabia'),
(56, 'Organic Liquid fertilizer exporter in oman', 'Best Organic Liquid fertilizer exporter in oman', '<p>Spraying liquid fertilizer directly onto leaves allows for quick absorption of nutrients. Ideal for correcting deficiencies or promoting growth during periods of rapid growth.\r\nSoil Drenching: Pouring liquid fertilizer directly onto the soil around plants ensures nutrients reach the root zone. Effective for ongoing nutrient maintenance and root development.</p>', 'Our commitment to leveraging the latest advancements in agricultural technology ensures that our customers stay at the forefront of industry trends and practices.', '', 'Organic-Liquid-fertilizer-exporter-in-oman'),
(57, 'Liquid fertilizer supplier in oman', 'Best Liquid fertilizer supplier in oman', '<p>\r\n Apply liquid fertilizers according to plant needs and growth stages. Too frequent application can lead to nutrient imbalances or salt buildup in the soil.\r\nStorage: Store liquid fertilizers in a cool, dry place away from direct sunlight to maintain their efficacy and prevent degradation.</p>', 'With a focus on research and development, we offer a diverse range of products tailored to meet the unique needs of every farmer. From traditional fertilizers to advanced bio-fertilizers and specialty nutrients, we have everything you need to nurture your crops and maximize profitability.', '', 'Liquid-fertilizer-supplier-in-oman'),
(58, 'Liquid fertilizer exporter in belgium', 'Best Liquid fertilizer exporter in belgium', '<p>Apply liquid fertilizers according to plant needs and growth stages. Too frequent application can lead to nutrient imbalances or salt buildup in the soil.Store liquid fertilizers in a cool, dry place away from direct sunlight to maintain their efficacy and prevent degradation.\r\nEnvironmental Impact</p>', 'But our commitment doesn\'t stop there. We\'re dedicated to sustainability at every step of the process, from production to distribution. By embracing eco-friendly practices and reducing our environmental footprint, we\'re working towards a greener, more sustainable future for agriculture.', '', 'Liquid-fertilizer-exporter-in-belgium'),
(59, 'Organic Liquid fertilizer supplier in netherlands', 'Best Organic Liquid fertilizer supplier in netherlands', '<p>Enrich soil fertility and balance nutrient levels with our organic amendments, which include natural inputs such as compost, manure, and biochar. These products replenish essential nutrients, improve soil structure, and support long-term soil health and productivity.</p>', 'Shreeji Agro & Fertilizers offers a diverse range of organic products designed to support sustainable agriculture and promote the health and vitality of crops. ', '', 'Organic-Liquid-fertilizer-supplier-in-netherlands'),
(60, 'Liquid fertilizer exporter in qatar', 'Best Liquid fertilizer exporter in qatar\n', '<p>But our commitment doesn\'t stop there. We\'re dedicated to sustainability at every step of the process, from production to distribution. By embracing eco-friendly practices and reducing our environmental footprint, we\'re working towards a greener, more sustainable future for agriculture.</p>', 'Experience the benefits of organic farming with Shreeji Agro & Fertilizers\' premium organic products – trusted solutions for healthier crops, stronger soils, and sustainable agricultural practices.', '', 'Liquid-fertilizer-exporter-in-qatar'),
(61, 'Liquid fertilizer supplier in qatar', 'Best Liquid fertilizer supplier in qatar', '<p>Founded on principles of integrity, innovation, and customer satisfaction, Shreeji Agro & Fertilizers strives to deliver products that ensure optimal crop health and yield. We understand the challenges faced by farmers today and are committed to offering reliable solutions that foster growth and prosperity in agriculture.</p>', 'At Shreeji Agro & Fertilizers, we uphold the highest standards of ethics and sustainability. We are committed to promoting eco-friendly practices and supporting farmers in adopting sustainable agricultural techniques that preserve natural resources for future generations.', '', 'Liquid-fertilizer-supplier-in-qatar'),
(62, 'Liquid fertilizer exporter in germany', 'Best Liquid fertilizer exporter in germany', '<p>At Shreeji Agro & Fertilizers, our mission is clear: to empower farmers with the tools and knowledge they need to achieve optimal crop yields sustainably. We strive to enhance agricultural productivity through the delivery of high-quality products and personalized agronomic support, ensuring that every farmer can maximize their harvest while preserving the environment for future generations.</p>', 'Explore our extensive selection of agricultural products, including fertilizers, crop protection solutions, agrochemicals, seeds, and seed treatments. Each product is carefully curated to meet the diverse needs of modern farming practices.', '', 'Liquid-fertilizer-exporter-in-germany'),
(63, 'Organic Liquid fertilizer supplier in germany', 'Best Organic Liquid fertilizer supplier in germany', '<p>Our Products and Services\r\n\r\nFertilizers: Enhance soil fertility and promote healthy plant growth with our range of high-quality fertilizers. From organic to specialized formulations, we have solutions tailored to meet the nutritional needs of different crops.\r\n\r\nCrop Protection: Safeguard your crops against pests, diseases, and weeds with our innovative crop protection solutions. Our products are designed to provide effective control while maintaining crop safety and environmental sustainability.\r\n\r\nAgrochemicals: Choose from a variety of herbicides, fungicides, and insecticides that ensure superior crop protection and yield optimization.\r\n\r\nSeeds and Seed Treatments: Discover superior-quality seeds and advanced seed treatments that improve germination rates, enhance crop resilience, and support higher yields.</p>', 'We prioritize quality at every step. Our products undergo rigorous testing and adhere to international standards to guarantee efficacy, safety, and reliability in the field.', '', 'Organic-Liquid-fertilizer-supplier-in-germany'),
(64, 'Liquid fertilizer exporters in spain ', 'best Liquid fertilizer exporters in spain ', '<p>At Shreeji Agro & Fertilizers, we prioritize our customers\' success. Whether you are a large-scale commercial farmer or a smallholder looking to improve your harvest, we are committed to delivering exceptional value through reliable products, technical expertise, and responsive service.</p>', 'Choose from a variety of herbicides, fungicides, and insecticides that ensure superior crop protection and yield optimization.', '', 'Liquid-fertilizer-exporters-in-spain '),
(65, 'Liquid fertilizer supplier in spain', 'best Liquid fertilizer supplier in spain', '<p>Natural Ingredients: Our liquid organic fertilizer is derived from organic sources such as plant extracts, animal by-products, and beneficial microbes, ensuring a sustainable and eco-friendly solution for your crops.</p>', 'Discover superior-quality seeds and advanced seed treatments that improve germination rates, enhance crop resilience, and support higher yields.', '', 'Liquid-fertilizer-supplier-in-spain'),
(66, 'Organic Liquid fertilizer supplier in united kingdom', 'best Organic Liquid fertilizer supplier in united kingdom', '<p>Safeguard your crops against pests, diseases, and weeds with our innovative crop protection solutions. Our products are designed to provide effective control while maintaining crop safety and environmental sustainability.</p>', ' We strive to enhance agricultural productivity through the delivery of high-quality products and personalized agronomic support, ensuring that every farmer can maximize their harvest while preserving the environment for future generations.', '', 'Organic-Liquid-fertilizer-supplier-in-united-kingdom'),
(67, 'Liquid fertilizer exporter in united kingdom', 'best  Liquid fertilizer exporter in united kingdom', '<p>Founded with a vision to cater to the evolving needs of agriculture, Shreeji Agro & Fertilizers has grown from a humble beginning to become a trusted name in the industry. Our journey is marked by a steadfast commitment to quality, innovation, and customer-centricity, which has earned us the reputation of being a reliable partner for agricultural success.</p>', ' We embrace innovation as a driving force behind our product development and operational practices, continually seeking new ways to enhance agricultural efficiency and sustainability.', '', 'Liquid-fertilizer-exporter-in-united-kingdom'),
(68, 'Organic Liquid fertilizer exporter in india', 'best Organic Liquid fertilizer exporter in india', '<p>Shreeji Agro & Fertilizers is proud to lead the way in agricultural innovation and best practices. We actively collaborate with agricultural experts, research institutions, and industry leaders to stay at the forefront of technological advancements and market trends. This enables us to deliver cutting-edge solutions that address the evolving challenges faced by farmers today.</p>', 'Shreeji Agro & Fertilizers is proud to lead the way in agricultural innovation and best practices. We actively collaborate with agricultural experts, research institutions, and industry leaders to stay at the forefront of technological advancements and market trends. This enables us to deliver cutting-edge solutions that address the evolving challenges faced by farmers today.', '', 'Organic-Liquid-fertilizer-exporter-in-india'),
(69, 'Liquid fertilizer exporter in australia', 'best Liquid fertilizer exporter in australia', '<p>Our Product Promise\r\n\r\nExplore our comprehensive range of agricultural products and services designed to meet the diverse needs of modern farming:\r\n\r\nFertilizers: From organic to specialized formulations, our fertilizers are formulated to improve soil fertility and optimize crop nutrition.\r\n\r\nCrop Protection: Our crop protection solutions offer effective control against pests, diseases, and weeds, ensuring crop health and yield protection.\r\n\r\nAgrochemicals: Choose from a wide selection of herbicides, fungicides, and insecticides that provide targeted solutions for crop management.\r\n\r\nSeeds and Seed Treatments: Discover high-quality seeds and advanced treatments that enhance seed performance and support higher yields.</p>', ' We actively collaborate with agricultural experts, research institutions, and industry leaders to stay at the forefront of technological advancements and market trends. This enables us to deliver cutting-edge solutions that address the evolving challenges faced by farmers today.', '', 'Liquid-fertilizer-exporter-in-australia'),
(70, 'Organic Liquid fertilizer exporter in vietnam', 'best Organic Liquid fertilizer exporter in vietnam', '<p>Sustainability is a cornerstone of our business philosophy. We recognize the importance of preserving natural resources and reducing our carbon footprint. Our sustainable farming initiatives include promoting organic farming practices, advocating for water conservation measures, and supporting biodiversity through integrated pest management strategies.</p>', 'Sustainability is a cornerstone of our business philosophy. We recognize the importance of preserving natural resources and reducing our carbon footprint. Our sustainable farming initiatives include promoting organic farming practices, advocating for water conservation measures, and supporting biodiversity through integrated pest management strategies.', '', 'Organic-Liquid-fertilizer-exporter-in-vietnam'),
(71, 'Organic Liquid fertilizer exporter in  austria', 'best Organic Liquid fertilizer exporter in  austria', '<p>Our commitment to quality and sustainability has been recognized through various industry certifications and awards. These accolades validate our efforts and inspire us to continue raising the bar in agricultural excellence. We are proud to be trusted by farmers and industry partners alike for our reliability and integrity.<p>', 'Our commitment to quality and sustainability has been recognized through various industry certifications and awards. These accolades validate our efforts and inspire us to continue raising the bar in agricultural excellence. We are proud to be trusted by farmers and industry partners alike for our reliability and integrity.', '', 'Organic-Liquid-fertilizer-exporter-in-austria'),
(72, 'Liquid fertilizer exporter in thailand', 'best Liquid fertilizer exporter in thailand', '<p>Shreeji Agro & Fertilizers was founded on the principles of integrity, innovation, and service. Our founder, envisioned a company that would not only provide essential agricultural products but also serve as a catalyst for positive change in the farming community. These principles continue to guide us as we navigate the complexities of modern agriculture.<p>', 'As we look to the future, Shreeji Agro & Fertilizers remains dedicated to innovation, sustainability, and customer satisfaction. We are committed to expanding our product portfolio, exploring new markets, and adapting to the evolving needs of agriculture. Our goal is to empower farmers with the tools and knowledge they need to succeed in a rapidly changing agricultural landscape.', '', 'Liquid-fertilizer-exporter-in-thailand');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `blog`
--
ALTER TABLE `blog`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `blog`
--
ALTER TABLE `blog`
  MODIFY `id` int(100) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=73;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
